language: generic

sudo: required

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake

# language: shell
script:
  - find . -iname "*.sh" | grep -v "test" | xargs shellcheck
  - BATS_RUN_SKIPPED=true ./test.sh

after_success:
  - wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz && tar xzf master.tar.gz && cd kcov-master && mkdir build && cd build && cmake .. && make && sudo make install && cd ../.. && rm -rf kcov-master && mkdir -p coverage && BATS_RUN_SKIPPED=true kcov coverage test.sh && bash <(curl -s https://codecov.io/bash)
