dist: bionic
language: generic

# sudo: required

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake

cache:
  directories:
  - "${HOME}/kcov/"

env:
- PATH=${PATH}:${HOME}/kcov/bin

before_install:
- wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz
install:
- tar xzf master.tar.gz
- cd kcov-master
- mkdir build
- cd build
- cmake -DCMAKE_INSTALL_PREFIX=${HOME}/kcov ..
- make
- make install
- cd ../..
- rm -rf kcov-master
- mkdir -p coverage
script:
- kcov "$PWD/coverage" ./test.sh
# - ./test.sh

after_success:
- bash <(curl -s https://codecov.io/bash)

# language: shell
# script:
  # - find . -iname "*.sh" | grep -v "test" | xargs shellcheck
  # - BATS_RUN_SKIPPED=true ./test.sh

# after_success:
  # - wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz && tar xzf master.tar.gz && cd kcov-master && mkdir build && cd build && cmake .. && make && sudo make install && cd ../.. && rm -rf kcov-master && mkdir -p coverage && kcov coverage test.sh && bash <(curl -s https://codecov.io/bash)
